#!/usr/bin/env bash

# macOS only
[[ ! "$(uname -s)" = "Darwin" ]] && \
echo "Hammerspoon is only available for macOS!" && \
return 1

# Git Repo
GH_USER="drliangjin"
GH_REPO=".hammerspoon.d"
GH_BRANCH="master"

# Hammerspoon configuration dir
HS_DIR="$HOME/${GH_REPO}"

# Spoon Archives
SPOONS_ARC="https://github.com/Hammerspoon/Spoons/raw/master/Spoons"
SPOONS_DIR="${HS_DIR}/Spoons"

# symlink
LINK_DIR="$HOME/.hammerspoon"

function command_exists() {
  command -v $1 > /dev/null 2>&1
}

# Homebrew
function install_homebrew() {
  if ! command_exists brew; then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" > /dev/null 2>&1
    if [[ $? != 0 ]]; then
      echo " => unable to install Homebrew!"
      return 1
    fi
  fi
}

# brew install
function brew_install() {
  local formulae=$1
  if [[ ! -z "${formulae}" ]]; then
    echo "Installing $formulae..."
    if ! brew list "${formulae}" > /dev/null 2>&1; then
      brew install "${formulae}" > /dev/null 2>&1 
      if [[ $? != 0 ]]; then
        echo " => unable to install "${formulae}" !"
        return 1
      else
        echo "Installing "${formulae}"...done "
      fi
    else
      echo "Installing "${formulae}"...skipped "
    fi
  fi
}

# cask install
function cask_install() {
  local formulae=$1
  if [[ ! -z "${formulae}" ]]; then
    echo "Installing $formulae..."
    if ! brew cask list "${formulae}" > /dev/null 2>&1; then
      brew cask install $formulae > /dev/null 2>&1 
      if [[ $? != 0 ]]; then
        echo " => unable to install $formulae !"
        return 1
      else
        echo "Installing $formulae...done "
      fi
    else
      echo "Installing "${formulae}"...skipped "
    fi
  fi
}

function git_clone() {
  local config_dir="${HS_DIR}"
  echo "Deploying Hammerspoon configuration..."
  if [[ ! -d "${config_dir}" ]]; then
    git clone -q -b ${GH_BRANCH} https://github.com/${GH_USER}/${GH_REPO}.git && \
    ln -sf ${HS_DIR} ${LINK_DIR} && \
    echo "Deploying Hammerspoon configuration...done "
  else
    echo "Deploying Hammerspoon configuration...skipped "
  fi
}

function download_spoon() {
  local spoon_name=$1
  if [[ ! -z "${spoon_name}" ]]; then
    local spoon_url="${SPOONS_ARC}/${spoon_name}.spoon.zip"
    local spoon_dir="${SPOONS_DIR}/${spoon_name}.spoon"
    echo "Downloading Spoon: ${spoon_name}..."
    if [[ ! -d "${spoon_dir}" ]]; then
      cd /tmp
      curl -fsSLO "${spoon_url}"
      mkdir -p "${SPOONS_DIR}" && unzip -q "${spoon_name}.spoon.zip" -d "${SPOONS_DIR}"
      if [[ $? != 0 ]]; then
        echo " => unable to download ${spoon_name} !"
        return 1
      else
        echo "Installing Spoon: ${spoon_name}...done "
      fi
    else
      echo "Installing Spoon: ${spoon_name}...skipped "
    fi
  fi
}

function main() {

  install_homebrew && \
  
  brew_install lua && \
  
  cask_install hammerspoon && \
  
  git_clone && \
  
  download_spoon SpoonInstall
}

main
