#!/usr/bin/env bash

# macOS only
[[ ! "$(uname -s)" = "Darwin" ]] && \
echo "Hammerspoon is only available for macOS!" && \
return 1

# Git Repo
GH_USER="drliangjin"
GH_REPO=".hammerspoon.d"
GH_BRANCH="master"

# Hammerspoon
HS_DIR="$HOME/${GH_REPO}"

# symlink
LINK_DIR="$HOME/.hammerspoon"

function command_exists() {
  command -v $1 > /dev/null 2>&1
}

# Homebrew
function install_homebrew() {
  if ! command_exists brew; then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" > /dev/null 2>&1
    if [[ $? != 0 ]]; then
      echo " => unable to install Homebrew!"
      return 1
    fi
  fi
}

# brew install
function brew_install() {
  local formulae=$1
  if [[ ! -z "${formulae}" ]]; then
    echo "Installing $formulae..."
    brew install $formulae > /dev/null 2>&1 
    if [[ $? != 0 ]]; then
      echo " => unable to install $formulae !"
      return 1
    else
      echo "Installing $formulae...done"
    fi
  fi
}

# cask install
function cask_install() {
  local formulae=$1
  if [[ ! -z "${formulae}" ]]; then
    echo "Installing $formulae..."
    brew cask install $formulae > /dev/null 2>&1 
    if [[ $? != 0 ]]; then
      echo " => unable to install $formulae !"
      return 1
    else
      echo "Installing $formulae...done"
    fi
  fi
}

function clone_config() {
  echo "Deploying Hammerspoon configuration..."
  git clone -q -b ${GH_BRANCH} https://github.com/${GH_USER}/${GH_REPO}.git && \
  ln -sf ${HS_DIR} ${LINK_DIR} && \
  echo "Deploying Hammerspoon configuration...done"
}

function download_spoon() {
  local spoon_name=$1
  if [[ ! -z "${spoon_name}" ]]; then
    local spoon_url="https://github.com/Hammerspoon/Spoons/raw/master/Spoons/${spoon_name}.spoon.zip"
    local spoon_dir="${HS_DIR}/Spoons"
    echo "Downloading Spoon: ${spoon_name}..."
    cd /tmp
    curl -fsSLO "${spoon_url}"
    mkdir -p "${spoon_dir}" && unzip -q "${spoon_name}.spoon.zip" -d "${spoon_dir}"
    if [[ $? != 0 ]]; then
      echo " => unable to download ${spoon_name} !"
      return 1
    else
      echo "Installing Spoon: ${spoon_name}...done"
    fi
  fi
}

function main() {

  install_homebrew &&\
  
  brew_install lua &&\
  
  cask_install hammerspoon &&\
  
  clone_config &&\
  
  download_spoon SpoonInstall
}

main
